// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klwjxagggueuqyzdkcdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsd2p4YWdnZ3VldXF5emRrY2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODQyNzMsImV4cCI6MjA3MjU2MDI3M30.h-YVjYbxUgMB_o8pkU-J-hclrLtNiX8yYrP2SDg9qVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});